### ISSUE TITLE
Tagging releases

### ISSUE THREAD

**Issue by prateek** [fortytw2/leaktest#26]
The latest release was tagged over a year ago. How would you feel about tagging releases more frequently?

**Comment by fortytw2** [comment]
1.2.0 was tagged on March 19 - I generally tag a new release when there are commits that impact the code itself, not just small typos / doc changes / etc. 

I just checked, and it looks like we're all good in terms of there being no particularly notable changes on master since 1.2.0 - if this is wrong, let me know. Generally leaktest is stable and should see relatively few changes.

**Comment by fortytw2** [comment]
Going to close this issue, let me know if you think it should be reopened.

**Comment by prateek** [comment]
@fortytw2 Cheers. For some reason I had in my mind that https://github.com/fortytw2/leaktest/commit/7dad53304f9614c1c365755c1176a8e876fee3e8 wasn't included in 1.2. Apologies for the noise.
